### PR TITLE
Fix map constructor syntax

### PR DESCRIPTION
**Pull request by joewiz**
See eXist-db/exist#2887.

### CODE REVIEW

**Review by dizzzz — APPROVED** [review]

**Comment by joewiz** [comment]
@dizzzz Thanks! Shall I prepare a new release, or would you prefer to do this? Either way is fine with me.

**Comment by dizzzz** [comment]
We indeed should prepare a new release, all is set for now. (htough it might be good to verify if the XAR works both on v4 and v5)

**Comment by joewiz** [comment]
@dizzzz Cool. Shall I just increment the version number (to a new patch release), build the xar and publish it - i.e., the old way? Or is the procedure outlined in https://github.com/eXist-db/jfreechart/issues/31 ready to go?

**Comment by PieterLamers** [comment]
jfreechart-showcase/modules/view.xql still has the following (using no longer supported `:=` map key:value separator):
``` xquery
let $config := map {
    $templates:CONFIG_APP_ROOT := $config:app-root,
    $templates:CONFIG_STOP_ON_ERROR := true()
}
```
fixed that on my localhost. Don't know how to push changes to GIT yet tho.

**Pull request merged**
